"[{\"text\":\"Gateways are not able to start again. Same auth issue?\",\"id\":\"1185140639726325790\",\"url\":\"https://discord.com/channels/638409433860407300/638411171233398824/1185140639726325790\",\"userId\":\"357250803695616003\",\"date\":1702629947359},{\"text\":\"THey are restarting with message like this : \\\"2023-12-15T07:11:52.363941\\\" level=fatal msg=\\\"Post \\\\\\\"https://bdn-api.blxrbdn.com/nodes\\\\\\\": dial tcp 34.224.162.7:443: connect: connection refused\\\"\",\"id\":\"1185140793539833976\",\"url\":\"https://discord.com/channels/638409433860407300/638411171233398824/1185140793539833976\",\"userId\":\"357250803695616003\",\"date\":1702629984031},{\"text\":\"<@357250803695616003> Could be related to the issue from yesterday, will have to check with the team.\",\"id\":\"1185223043728015391\",\"url\":\"https://discord.com/channels/638409433860407300/638411171233398824/1185223043728015391\",\"userId\":\"945399314539216917\",\"date\":1702649594004,\"replyTo\":\"1185140639726325790\"}]"